name: 'default'

on:
  push:
  pull-request:

jobs:
  readiness:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: 'setup node'
        with:
          node-version: '13.x'

      - name: 'install'
        run: yarn install

      - name: 'test'
        run: yarn test